version: '3'

services:
  server:
    container_name: expo-notifications-server
    command: npm run dev
    restart: always
    volumes:
      - .:/usr/app/server
    environment:
      NODE_ENV: development
    ports:
      - '4000:4000'
    tty: true
    build: .
    depends_on:
      - database

  database:
    container_name: expo-notifications-mongo
    image: mongo
    ports:
      - '27017:27017'
